<div class="pdf-container">
    <!-- Header -->
    <div class="pdf-header">
        <h2>Product Sales Report</h2>
        <p><strong>Date Generated:</strong> {{ now()->format('F j, Y g:i A') }}</p>
    </div>

    <!-- Table -->
    <div class="pdf-card">
        <table>
            <thead>
                <tr>
                    <th>Transaction Code</th>
                    <th>Buyer</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Payment Method</th>
                    <th>Status</th>
                    <th>Date Order</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($orders as $order)
                <tr>
                    <td><strong>{{ $order->transaction_code }}</strong></td>
                    <td>{{ $order->user->name }}</td>
                    <td class="text-capitalize">{{ $order->product->product_name }}</td>
                    <td>P{{ number_format($order->order_price, 2, '.', ',') }}</td>
                    <td>{{ number_format($order->order_quantity) }} PC(s)</td>
                    <td><strong>P{{ number_format($order->order_total_amount, 2, '.', ',') }}</strong></td>
                    <td>{{ $order->order_payment_method }}</td>
                    <td class="status">
                        @if ($order->order_status === 'Pending')
                        <span class="badge badge-warning">PENDING</span>
                        @else
                        <span class="badge badge-success">PAID</span>
                        @endif
                    </td>
                    <td>{{ date_format($order->created_at, 'F j, Y g:i A') }}</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="grand-total-label">Grand Total:</td>
                    <td class="grand-total-value">P{{ number_format($grandTotal, 2, '.', ',') }}</td>
                    <td colspan="3" class="grand-total-label"></td>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- Footer -->
    <div class="pdf-footer">
        <p>Report Generated by <strong>AJM Company</strong></p>
    </div>
</div>

<!-- Styles for PDF -->
<style>
    /* Global Styling */
    body {
        font-family: 'Arial', sans-serif;
        font-size: 8px;
    }

    .pdf-container {
        width: 90%;
        margin: auto;
        padding: 20px;
        background: white;
        border-radius: 10px;
    }

    /* Header Styling */
    .pdf-header {
        text-align: center;
        padding: 10px 0;
        border-bottom: 3px solid #007BFF;
        margin-bottom: 20px;
    }

    .pdf-header h2 {
        color: #007BFF;
        margin: 0;
        font-size: 18px;
        font-weight: bold;
    }

    .pdf-header p {
        font-size: 12px;
        color: #666;
    }

    /* Table Card */
    .pdf-card {
        padding: 15px;
        border-radius: 8px;
    }

    /* Table Styling */
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
    }

    th,
    td {
        padding: 10px;
        text-align: left;
        border: 1px solid #ddd;
    }

    th {
        background: #007BFF;
        color: white;
        font-size: 13px;
    }

    tbody tr:nth-child(odd) {
        background: #f9f9f9;
    }

    tbody tr:hover {
        background: #eef7ff;
    }

    .status {
        text-align: center;
    }

    .badge-warning {
        background: #ffc107;
        color: black;
        padding: 4px 8px;
        border-radius: 4px;
    }

    .badge-success {
        background: #28a745;
        color: white;
        padding: 4px 8px;
        border-radius: 4px;
    }

    /* Grand Total */
    .grand-total-label {
        font-weight: bold;
        text-align: right;
        background: #007BFF;
        color: white;
    }

    .grand-total-value {
        font-weight: bold;
        font-size: 14px;
        background: #007BFF;
        color: white;
        text-align: left;
    }

    /* Footer */
    .pdf-footer {
        text-align: center;
        font-size: 11px;
        margin-top: 20px;
        padding-top: 10px;
        border-top: 1px solid #ddd;
        color: #555;
    }
</style>
