version: '3.8'

services:
    e-commerce-app2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: e-commerce-app2
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
             - .:/var/www/html
             - ./local.ini:/usr/local/etc/php/conf.d/local.ini
             #- /home/webserver/uploads/product_sales:/var/www/html/storage/app/public
             - ./storage/app:/var/www/html/storage/app
        environment:
            APP_ENV: production
            APP_URL: https://product.smctgroup.ph/
            DB_CONNECTION: mysql
            DB_HOST: 172.17.0.1
            DB_PORT: 3306
            DB_DATABASE: product_sales
            DB_USERNAME: smct
            DB_PASSWORD: smct
        command: >
            sh -c "composer install --no-dev --optimize-autoloader &&
                   npm install &&
                   npm run build &&
                   php-fpm"
        networks:
            - e-commerce-network2
    e-commerce-nginx2:
        image: nginx:alpine
        container_name: e-commerce-nginx2
        restart: unless-stopped
        ports:
            - "9004:9004"
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./storage/app:/var/www/html/storage/app
        depends_on:
            - e-commerce-app2
        networks:
            - e-commerce-network2

networks:
    e-commerce-network2:
        driver: bridge  
